# Generated by Django 5.0.14 on 2026-03-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_p_timesta_a6e9e7_idx',
            old_name='analytics_p_timestmp_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_p_device__051b38_idx',
            old_name='analytics_p_device_f_idx',
        ),
    ]
