"""
Utility helpers for the standalone email service.

All functions here are pure (no DB calls) unless explicitly noted.
"""

import hashlib
import hmac
import logging
import re
import time
import unicodedata
from email.headerregistry import Address
from typing import Optional

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import validate_email as django_validate_email

logger = logging.getLogger('email.utils')

# ---------------------------------------------------------------------------
# Shared secret helpers
# ---------------------------------------------------------------------------

def _get_unsubscribe_secret() -> str:
    """
    Return the HMAC signing secret for unsubscribe tokens.
    Raises RuntimeError in production if the secret is not explicitly set.
    """
    secret = getattr(settings, 'EMAIL_UNSUBSCRIBE_SECRET', '') or ''
    if not secret:
        # In development fall back to SECRET_KEY so token generation works
        # without configuration.  In production the setting is mandatory.
        if not getattr(settings, 'DEBUG', False):
            raise RuntimeError(
                'EMAIL_UNSUBSCRIBE_SECRET must be set in production. '
                'Add it to your environment and settings.py.'
            )
        secret = settings.SECRET_KEY
    return secret


def _get_tracking_secret() -> str:
    """Return the HMAC secret for tracking pixel tokens (from settings)."""
    cfg = getattr(settings, 'EMAIL_SERVICE_CONFIG', {})
    secret = cfg.get('tracking_secret', '') or ''
    if not secret:
        secret = settings.SECRET_KEY
    return secret


# ---------------------------------------------------------------------------
# Token generation
# ---------------------------------------------------------------------------

def generate_unsubscribe_token(email: str, categories: Optional[list] = None) -> str:
    """
    Generate a cryptographically secure HMAC-signed unsubscribe token.

    Token format: ``{timestamp}.{hmac}``

    The token encodes the recipient email and (optionally) a comma-separated
    list of category names so phishing attempts targeting different categories
    are blocked.

    Args:
        email:      The recipient email address being unsubscribed.
        categories: List of email category strings to unsubscribe from.
                    None / empty list means unsubscribe from everything.

    Returns:
        A URL-safe token string.
    """
    email = email.lower().strip()
    categories_str = ','.join(sorted(categories or []))
    ts = str(int(time.time()))
    message = f'{email}:{categories_str}:{ts}'
    secret = _get_unsubscribe_secret()
    sig = hmac.new(
        secret.encode('utf-8'),
        message.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()
    return f'{ts}.{sig}'


def verify_unsubscribe_token(
    token: str,
    email: str,
    categories: Optional[list] = None,
    max_age_seconds: int = 86400 * 7,  # 7 days
) -> bool:
    """
    Validate an unsubscribe token previously generated by ``generate_unsubscribe_token``.

    Returns True only when the signature is valid and the token has not expired.
    """
    try:
        ts_str, sig = token.split('.', 1)
        ts = int(ts_str)
    except (ValueError, AttributeError):
        return False

    if max_age_seconds and (int(time.time()) - ts) > max_age_seconds:
        return False

    email = email.lower().strip()
    categories_str = ','.join(sorted(categories or []))
    message = f'{email}:{categories_str}:{ts_str}'
    secret = _get_unsubscribe_secret()
    expected = hmac.new(
        secret.encode('utf-8'),
        message.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()
    return hmac.compare_digest(expected, sig)


def generate_tracking_pixel_token(email_message_id: str) -> str:
    """
    Generate a signed token for the email open-tracking pixel URL.

    Args:
        email_message_id: The UUID string of the EmailMessage record.

    Returns:
        A compact HMAC-signed token.
    """
    ts = str(int(time.time()))
    message = f'{email_message_id}:{ts}'
    secret = _get_tracking_secret()
    sig = hmac.new(
        secret.encode('utf-8'),
        message.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()[:32]  # Truncate — still 128-bit security
    return f'{ts}.{sig}'


def verify_tracking_pixel_token(
    token: str,
    email_message_id: str,
    max_age_seconds: int = 86400 * 30,  # 30 days
) -> bool:
    """
    Validate a tracking pixel token.

    Returns True only when the signature is valid and the token is not expired.
    """
    try:
        ts_str, sig = token.split('.', 1)
        ts = int(ts_str)
    except (ValueError, AttributeError):
        return False

    if max_age_seconds and (int(time.time()) - ts) > max_age_seconds:
        return False

    message = f'{email_message_id}:{ts_str}'
    secret = _get_tracking_secret()
    expected = hmac.new(
        secret.encode('utf-8'),
        message.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()[:32]
    return hmac.compare_digest(expected, sig)


# ---------------------------------------------------------------------------
# Email validation and sanitisation
# ---------------------------------------------------------------------------

_EMAIL_PATTERN = re.compile(
    r'^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$',
    re.IGNORECASE,
)


def validate_email_address(email: str) -> str:
    """
    Validate an email address using Django's built-in validator plus a
    secondary regex check.

    Returns:
        The normalised email address (stripped + lowercased).

    Raises:
        ValueError: if the address is not valid.
    """
    if not email or not isinstance(email, str):
        raise ValueError('Email address must be a non-empty string.')

    email = email.strip()

    # Django's validator covers most RFC 5321 rules
    try:
        django_validate_email(email)
    except ValidationError as exc:
        raise ValueError(f'Invalid email address: {email!r} — {exc.message}') from exc

    # Additional regex sanity check (rejects unusual but technically valid forms)
    if not _EMAIL_PATTERN.match(email):
        raise ValueError(f'Email address has an unsupported format: {email!r}')

    return email.lower()


def sanitize_email_input(value: str, max_length: int = 255) -> str:
    """
    Sanitise a string that will be used inside an email template or header.

    - Strips leading/trailing whitespace
    - Removes ASCII control characters (0x00–0x1F except tab/newline)
    - Normalises Unicode to NFC form
    - Truncates to ``max_length`` characters

    This does *not* HTML-escape — Django's template engine handles that when
    using ``{{ variable }}`` syntax.  Use mark_safe() only for trusted content.

    Args:
        value:      The string to sanitise.
        max_length: Maximum allowed length (default 255).

    Returns:
        A sanitised string.
    """
    if not isinstance(value, str):
        value = str(value)

    # Normalise Unicode
    value = unicodedata.normalize('NFC', value)

    # Remove ASCII control characters (except \t and \n which are safe in text)
    value = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', value)

    # Strip surrounding whitespace
    value = value.strip()

    # Truncate
    if len(value) > max_length:
        value = value[:max_length]

    return value


def build_unsubscribe_url(email: str, categories: Optional[list] = None) -> str:
    """
    Build the full unsubscribe URL for embedding in email templates.

    Args:
        email:      Recipient email address.
        categories: Optional list of category strings; None = all.

    Returns:
        Absolute URL string.
    """
    from urllib.parse import quote_plus
    token = generate_unsubscribe_token(email, categories)
    base = _get_tracking_base_url().rstrip('/')
    return f'{base}/unsubscribe/?e={quote_plus(email)}&t={token}'


def build_tracking_pixel_url(email_message_id: str) -> str:
    """
    Build the URL for the email open-tracking pixel.

    Args:
        email_message_id: UUID string of the EmailMessage record.

    Returns:
        Absolute URL string for a 1×1 transparent GIF endpoint.
    """
    token = generate_tracking_pixel_token(email_message_id)
    base = _get_tracking_base_url().rstrip('/')
    return f'{base}/email/track/open/{email_message_id}/?t={token}'


def _get_tracking_base_url() -> str:
    cfg = getattr(settings, 'EMAIL_SERVICE_CONFIG', {})
    return cfg.get('tracking_base_url', '') or getattr(settings, 'SITE_URL', 'http://localhost:8000')


# ---------------------------------------------------------------------------
# Domain extraction
# ---------------------------------------------------------------------------

def extract_email_domain(email: str) -> str:
    """
    Extract the domain component from an email address.

    >>> extract_email_domain('user@example.com')
    'example.com'
    >>> extract_email_domain('bad-address')
    ''
    """
    try:
        return email.strip().split('@', 1)[1].lower()
    except (IndexError, AttributeError):
        return ''


# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------

def get_email_type_display(email_type: str) -> str:
    """Return a human-friendly label for an EmailType constant."""
    from .constants import EmailType
    return dict(EmailType.choices).get(email_type, email_type)
