# Generated by Django 5.0.14 on 2026-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('SYSTEM_ALERT', 'System Alert'), ('ADMIN_MESSAGE', 'Admin Message'), ('SECURITY_EVENT', 'Security Event'), ('ROLE_UPDATED', 'Role Updated'), ('PERMISSIONS_UPDATED', 'Permissions Updated')], db_index=True, max_length=50),
        ),
    ]
