# Generated by Django 5.0.14 on 2026-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('WITHDRAWAL_INITIATED', 'Withdrawal Initiated'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_PROCESSING', 'Withdrawal Processing'), ('WITHDRAWAL_OTP_REQUIRED', 'Withdrawal OTP Required'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('WITHDRAWAL_FAILED', 'Withdrawal Failed'), ('SYSTEM_ALERT', 'System Alert'), ('ADMIN_MESSAGE', 'Admin Message'), ('SECURITY_EVENT', 'Security Event'), ('ROLE_UPDATED', 'Role Updated'), ('PERMISSIONS_UPDATED', 'Permissions Updated')], db_index=True, max_length=50),
        ),
    ]
