# Generated by Django 5.0.14 on 2026-03-06 19:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GivingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Tithes', 'Tithes'), ('Offerings', 'Offerings'), ('Projects', 'Projects'), ('Fundraising', 'Fundraising')], db_index=True, default='Tithes', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='volunteer_activism', max_length=50)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS_ONLY', 'Members Only'), ('HIDDEN', 'Hidden')], db_index=True, default='PUBLIC', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_recurring_enabled', models.BooleanField(default=False)),
                ('suggested_amounts', models.JSONField(blank=True, default=list, help_text='List of suggested donation amounts')),
                ('goal_amount', models.PositiveBigIntegerField(blank=True, help_text='Fundraising goal in smallest currency unit (kobo/cent)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('raised_amount', models.PositiveBigIntegerField(default=0, help_text='Total raised so far in smallest currency unit')),
                ('deadline', models.DateField(blank=True, help_text='Campaign deadline (optional)', null=True)),
                ('verse', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first')),
                ('total_donations', models.PositiveBigIntegerField(default=0, help_text='Cached total donations count')),
                ('donor_count', models.PositiveIntegerField(default=0, help_text='Cached unique donor count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'giving_items',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'visibility'], name='giving_item_status_99cd18_idx'), models.Index(fields=['category', 'status'], name='giving_item_categor_fd3e6a_idx')],
            },
        ),
    ]
