# Generated by Django 5.0.14 on 2026-03-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_con_status_4b75ca_idx',
            old_name='contact_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_con_categor_53fb77_idx',
            old_name='contact_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_con_sender__01d88d_idx',
            old_name='contact_email_idx',
        ),
    ]
