# Generated by Django 5.0.14 on 2026-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_subscribed_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('MEMBER', 'Member'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='VISITOR', help_text='User role for access control', max_length=10),
        ),
    ]
