# Generated by Django 5.0.14 on 2026-02-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time verification email was sent (for rate limiting)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Hashed email verification token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time for email verification token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when email was verified', null=True),
        ),
    ]
