# Generated by Django 5.0.14 on 2026-03-07 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=list, help_text='List of permission code strings granted to this moderator')),
                ('sub_role_label', models.CharField(blank=True, help_text='Human-readable label for the moderator sub-role (e.g. "Finance Moderator")', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated these permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Moderator user these permissions apply to', on_delete=django.db.models.deletion.CASCADE, related_name='mod_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderator Permission',
                'verbose_name_plural': 'Moderator Permissions',
                'db_table': 'moderator_permissions',
            },
        ),
    ]
