# Generated by Django 5.0.14 on 2026-03-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_moderatorpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account subject identifier for OAuth-linked accounts', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_profile_picture_url',
            field=models.URLField(blank=True, help_text='Google-hosted profile picture URL for OAuth-linked accounts', null=True),
        ),
    ]
