# Generated by Django 5.0.14 on 2026-02-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='series',
            new_name='series_seri_slug_bda3af_idx',
            old_name='series_seri_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='series_seri_author__a9c116_idx',
            old_name='series_seri_author_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='series_seri_is_feat_2372d6_idx',
            old_name='series_seri_is_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='series_seri_visibil_c3c484_idx',
            old_name='series_seri_visibil_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='series_seri_is_dele_621715_idx',
            old_name='series_seri_is_dele_idx',
        ),
    ]
