# Generated by Django 5.0.14 on 2026-03-25 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_alter_privacypolicy_content'),
        ('series', '0004_currentseriesspotlight_part_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesAnnouncementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('NEW_ARTICLE', 'New Article Update')], default='ANNOUNCEMENT', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_ADMIN_APPROVAL', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING_ADMIN_APPROVAL', max_length=32)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_completed_at', models.DateTimeField(blank=True, null=True)),
                ('audience_snapshot_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_series_announcement_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_series_announcement_requests', to=settings.AUTH_USER_MODEL)),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_announcement_requests', to='content.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_requests', to='series.series')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['series', 'status', '-created_at'], name='series_seri_series__e697af_idx'), models.Index(fields=['created_by', 'status', '-created_at'], name='series_seri_created_ac8cbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeriesSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('UNSUBSCRIBED', 'Unsubscribed')], default='PENDING_VERIFICATION', max_length=30)),
                ('verification_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('verification_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='series.series')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['series', 'status'], name='series_seri_series__83534e_idx'), models.Index(fields=['email', 'status'], name='series_seri_email_219f74_idx'), models.Index(fields=['user', 'status'], name='series_seri_user_id_2873c2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seriessubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('series', 'user'), name='uniq_series_subscription_user'),
        ),
        migrations.AddConstraint(
            model_name='seriessubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('email', ''), _negated=True)), fields=('series', 'email'), name='uniq_series_subscription_public_email'),
        ),
    ]
