# Generated by Django 5.0.14 on 2026-03-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_seriesannouncementrequest_seriessubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesannouncementrequest',
            name='audience_snapshot_frozen_at',
            field=models.DateTimeField(blank=True, help_text='When the subscriber audience was frozen for delivery.', null=True),
        ),
        migrations.AlterField(
            model_name='seriesannouncementrequest',
            name='audience_snapshot_count',
            field=models.IntegerField(default=0, help_text='Number of active subscribers frozen at admin-approval time.'),
        ),
        migrations.AlterField(
            model_name='seriesannouncementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_ADMIN_APPROVAL', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING_ADMIN_APPROVAL', max_length=32),
        ),
    ]
