# Generated by Django 5.0.14 on 2026-01-20 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('SERMON', 'Sermon'), ('ANNOUNCEMENT', 'Announcement'), ('ARTICLE', 'Article'), ('DEVOTIONAL', 'Devotional')], default='ARTICLE', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('reactions_enabled', models.BooleanField(default=True)),
                ('featured_image', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='content_pos_created_415459_idx'), models.Index(fields=['post_type', '-created_at'], name='content_pos_post_ty_96c246_idx'), models.Index(fields=['is_published', '-published_at'], name='content_pos_is_publ_3f799d_idx')],
            },
        ),
    ]
