# Generated by Django 5.0.14 on 2026-01-20 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_priority',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first in featured section'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', '-featured_priority'], name='content_pos_is_feat_1717ce_idx'),
        ),
    ]
