# Generated by Django 5.0.14 on 2026-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_featured_priority_post_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
