# Generated by Django 5.0.14 on 2026-01-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Publishing status: DRAFT, SCHEDULED, or PUBLISHED', max_length=20),
        ),
    ]
