# Generated by Django 5.0.14 on 2026-01-22 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_post_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('SERMON', 'Sermon'), ('ANNOUNCEMENT', 'Announcement'), ('ARTICLE', 'Article'), ('DEVOTIONAL', 'Devotional')], default='ARTICLE', help_text='[DEPRECATED] Use content_type instead', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Publishing status: DRAFT or PUBLISHED', max_length=20),
        ),
        migrations.CreateModel(
            name='PostContentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="Immutable identifier (e.g., 'sermon', 'announcement')", unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Sermon', 'Announcement')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for admins')),
                ('is_system', models.BooleanField(default=False, help_text='System types cannot be edited or deleted')),
                ('is_enabled', models.BooleanField(default=True, help_text='Only enabled types appear in post creation dropdowns')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_enabled', 'sort_order'], name='content_pos_is_enab_7cfceb_idx')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Dynamic content type (Sermon, Announcement, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='content.postcontenttype'),
        ),
    ]
