# Generated by Django 5.0.14 on 2026-01-22 10:31

from django.db import migrations
import uuid


def seed_system_content_types(apps, schema_editor):
    """
    Seed the three required system content types:
    - announcement
    - sermon  
    - article
    
    These are immutable and cannot be deleted.
    """
    PostContentType = apps.get_model('content', 'PostContentType')
    
    # Define system types (matching the old PostType enum)
    system_types = [
        {
            'slug': 'announcement',
            'name': 'Announcement',
            'description': 'Church announcements and updates',
            'is_system': True,
            'is_enabled': True,
            'sort_order': 1,
        },
        {
            'slug': 'sermon',
            'name': 'Sermon',
            'description': 'Sunday sermons and teachings',
            'is_system': True,
            'is_enabled': True,
            'sort_order': 2,
        },
        {
            'slug': 'article',
            'name': 'Article',
            'description': 'General articles and blog posts',
            'is_system': True,
            'is_enabled': True,
            'sort_order': 3,
        },
    ]
    
    # Create system types (idempotent - won't duplicate if run multiple times)
    for type_data in system_types:
        PostContentType.objects.get_or_create(
            slug=type_data['slug'],
            defaults=type_data
        )


def migrate_existing_posts(apps, schema_editor):
    """
    Migrate existing posts from post_type (CharField) to content_type (ForeignKey).
    Maps old enum values to new PostContentType records.
    """
    Post = apps.get_model('content', 'Post')
    PostContentType = apps.get_model('content', 'PostContentType')
    
    # Mapping from old post_type values to content_type slugs
    type_mapping = {
        'ANNOUNCEMENT': 'announcement',
        'SERMON': 'sermon',
        'ARTICLE': 'article',
        'DEVOTIONAL': 'article',  # Map DEVOTIONAL to article (was not in system types)
    }
    
    # Get all content types for efficient lookup
    content_types = {ct.slug: ct for ct in PostContentType.objects.all()}
    
    # Migrate all posts
    posts_updated = 0
    for post in Post.objects.filter(content_type__isnull=True):
        old_type = post.post_type
        new_slug = type_mapping.get(old_type, 'article')  # Default to article
        
        if new_slug in content_types:
            post.content_type = content_types[new_slug]
            post.save(update_fields=['content_type'])
            posts_updated += 1
    
    print(f"Migrated {posts_updated} posts to new content_type system")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - clear content_type FK (keep post_type for rollback safety)
    """
    Post = apps.get_model('content', 'Post')
    Post.objects.update(content_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_post_post_type_alter_post_status_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_system_content_types, reverse_migration),
        migrations.RunPython(migrate_existing_posts, reverse_migration),
    ]
