# Generated by Django 5.0.14 on 2026-01-22 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_seed_system_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment or question text')),
                ('type', models.CharField(choices=[('COMMENT', 'Comment'), ('QUESTION', 'Question'), ('FLAGGED', 'Flagged Comment')], db_index=True, default='COMMENT', max_length=20)),
                ('is_question', models.BooleanField(default=False, help_text='Is this a question requiring response?')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed'), ('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('ACTIONED', 'Actioned')], db_index=True, default='OPEN', max_length=20)),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='Has been flagged as inappropriate')),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True, help_text='Reason for flagging')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden from public view')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_interactions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.interaction')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='content.post')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_interactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'is_deleted'], name='content_int_post_id_111756_idx'), models.Index(fields=['user', 'is_deleted'], name='content_int_user_id_47c7e3_idx'), models.Index(fields=['type', 'status'], name='content_int_type_6255dc_idx'), models.Index(fields=['is_question', 'status'], name='content_int_is_ques_137844_idx'), models.Index(fields=['is_flagged', 'status'], name='content_int_is_flag_412ef4_idx')],
            },
        ),
    ]
