# Generated by Django 5.0.14 on 2026-02-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_post_series_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='content_pos_series__6962a2_idx',
            old_name='content_post_series_idx',
        ),
    ]
