# Generated by Django 5.0.14 on 2026-02-14 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_rename_content_post_series_idx_content_pos_series__6962a2_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_title', models.CharField(blank=True, help_text='Working title for identification', max_length=255)),
                ('draft_data', models.JSONField(help_text='Complete form state including title, content, settings, etc.')),
                ('version', models.IntegerField(default=1, help_text='Auto-increment on each save for future version history')),
                ('is_published_draft', models.BooleanField(default=False, help_text='Whether this draft is for content that was previously published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_autosave_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of this draft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='content.postcontenttype')),
                ('post', models.ForeignKey(blank=True, help_text='Linked post if editing existing content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='content.post')),
                ('user', models.ForeignKey(help_text='User who owns this draft', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draft',
                'verbose_name_plural': 'Drafts',
                'ordering': ['-last_autosave_at'],
                'indexes': [models.Index(fields=['user', '-last_autosave_at'], name='content_dra_user_id_b30b18_idx'), models.Index(fields=['post', 'user'], name='content_dra_post_id_5ef571_idx'), models.Index(fields=['-last_autosave_at'], name='content_dra_last_au_ac6abf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post'), name='unique_user_post_draft'),
        ),
    ]
