# Generated by Django 5.0.14 on 2026-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_draft_draft_unique_user_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='Faith', help_text='Content category/topic (e.g., Mental Health, Prayer, Marriage)', max_length=50),
        ),
    ]
