# Generated by Django 5.0.14 on 2026-03-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_add_daily_word_and_weekly_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='content_pos_schedul_6395fa_idx',
            old_name='content_post_scheduled_date_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='content_pos_schedul_fa2824_idx',
            old_name='content_post_scheduled_status_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='content_pos_schedul_e0944e_idx',
            old_name='content_post_scheduled_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyevent',
            new_name='content_wee_day_of__e20cbd_idx',
            old_name='content_week_day_of_week_idx',
        ),
    ]
