# Generated by Django 5.0.14 on 2026-03-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_seed_weekly_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prayer',
            field=models.TextField(blank=True, help_text='Prayer text (for devotional content)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scripture',
            field=models.TextField(blank=True, help_text='Scripture reference or verse (for devotional content)', null=True),
        ),
    ]
