# Generated by Django 5.0.14 on 2026-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_post_prayer_post_scripture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Publishing status: DRAFT or PUBLISHED', max_length=20),
        ),
    ]
