# Generated by Django 5.0.14 on 2026-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_convert_system_to_custom_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main heading (e.g., 'Finding Peace in the Midst of Chaos')", max_length=200)),
                ('description', models.TextField(help_text='Subtitle/description text')),
                ('label', models.CharField(default='Latest Sabbath Teaching', help_text="Category label above title (e.g., 'Latest Sabbath Teaching')", max_length=100)),
                ('image', models.ImageField(help_text='Hero section image', upload_to='hero_images/')),
                ('image_alt_text', models.CharField(default='Church content image', help_text='Alt text for accessibility', max_length=255)),
                ('button1_label', models.CharField(default='Watch Sermon', help_text='Text for primary button', max_length=100)),
                ('button1_url', models.URLField(blank=True, help_text='URL or action for primary button')),
                ('button1_icon', models.CharField(default='play_circle', help_text='Icon name from Icon component', max_length=50)),
                ('button2_label', models.CharField(default='Listen Audio', help_text='Text for secondary button', max_length=100)),
                ('button2_url', models.URLField(blank=True, help_text='URL or action for secondary button')),
                ('button2_icon', models.CharField(blank=True, help_text='Icon name from Icon component', max_length=50)),
                ('hero_type', models.CharField(choices=[('featured_sermon', 'Featured Sermon'), ('announcement', 'Announcement'), ('event', 'Event')], default='featured_sermon', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hero section is currently displayed')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Order of display if multiple hero sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Admin who last updated this hero section', max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-display_order', '-updated_at'],
            },
        ),
    ]
