# Generated by Django 5.0.14 on 2026-03-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_convert_system_to_custom_types'),
        ('content', '0023_herosection'),
    ]

    operations = [
    ]
