# Generated by Django 5.0.14 on 2026-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_merge_20260315_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero section image', null=True, upload_to='hero_images/'),
        ),
    ]
