# Generated by Django 5.0.14 on 2026-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_herosection_image_blank_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Testimonial title (e.g., 'A Journey to Stillness')", max_length=200)),
                ('name', models.CharField(help_text='Testimonial giver name (e.g., "James\' Story")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description or subtitle', null=True)),
                ('video_file', models.FileField(help_text='Video file (mp4, webm recommend)', upload_to='testimonials/videos/')),
                ('thumbnail_image', models.ImageField(help_text='Thumbnail image displayed before video plays', upload_to='testimonials/thumbnails/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this testimonial appears on public page')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower = shown first in infinite scroll)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Admin who last updated this testimonial', max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', '-display_order'], name='content_tes_is_acti_17199a_idx')],
            },
        ),
    ]
