# Generated by Django 5.0.14 on 2026-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('card_type', models.CharField(choices=[('group', 'Group'), ('serve', 'Serve Team'), ('event', 'Event')], default='group', max_length=20)),
                ('style_variant', models.CharField(choices=[('featured_group', 'Featured Group'), ('sand_serve', 'Sand Serve Card'), ('standard_group', 'Standard Group'), ('outlined_serve', 'Outlined Serve Card'), ('featured_event', 'Featured Event')], default='standard_group', max_length=30)),
                ('category_label', models.CharField(blank=True, max_length=80)),
                ('schedule_label', models.CharField(blank=True, max_length=120)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('date_label', models.CharField(blank=True, max_length=120)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Connect Ministry',
                'verbose_name_plural': 'Connect Ministries',
                'ordering': ['display_order', '-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='spiritualpractice',
            new_name='content_spi_is_acti_86264a_idx',
            old_name='content_spi_is_acti_261b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='spiritualpractice',
            new_name='content_spi_slug_982827_idx',
            old_name='content_spi_slug_df9e4a_idx',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='Display order (lower number appears first)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this story appears on the public page'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text="Story author label (e.g., James' Story)", max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='thumbnail_image',
            field=models.ImageField(help_text='Thumbnail image displayed before playback', upload_to='testimonials/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(help_text="Story title (e.g., 'A Journey to Stillness')", max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Admin who last updated this story', max_length=100),
        ),
        migrations.AddIndex(
            model_name='connectministry',
            index=models.Index(fields=['is_active', 'display_order'], name='content_con_is_acti_c52074_idx'),
        ),
        migrations.AddIndex(
            model_name='connectministry',
            index=models.Index(fields=['card_type', 'is_active'], name='content_con_card_ty_9951d9_idx'),
        ),
        migrations.AddIndex(
            model_name='connectministry',
            index=models.Index(fields=['slug'], name='content_con_slug_482311_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectministry',
            constraint=models.UniqueConstraint(fields=('display_order',), name='content_connectministry_unique_display_order'),
        ),
    ]
