# Generated by Django 5.0.14 on 2026-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_seed_connect_ministries_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectministry',
            name='cta_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='connectministry',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
