# Generated by Django 5.0.14 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_alter_connectministry_cta_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('content', models.TextField(default='<h2>Introduction</h2>\n<p>We value your trust and are committed to protecting your personal information.</p>\n<h2>Information We Collect</h2>\n<p>We may collect contact details, account information, and engagement activity necessary to provide church services.</p>\n<h2>How We Use Information</h2>\n<p>We use information to communicate with you, improve ministry programs, and support community care.</p>\n<h2>Data Sharing</h2>\n<p>We do not sell personal information. We only share data with trusted providers required to run core platform services.</p>\n<h2>Contact</h2>\n<p>If you have questions about this policy, please contact the church administration team.</p>')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Admin who last updated this privacy policy', max_length=100)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
