# Generated by Django 5.0.14 on 2026-01-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('AMEN', 'Amen'), ('INSIGHTFUL', 'Insightful')], default='LIKE', max_length=10),
        ),
    ]
