# Generated by Django 5.0.14 on 2026-01-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_update_reaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(default='👍', help_text='Emoji representation of reaction', max_length=10),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('LIKE', 'Like (👍)'), ('AMEN', 'Amen (🙏)'), ('LOVE', 'Love (❤️)'), ('INSIGHT', 'Insight (💡)'), ('PRAISE', 'Praise (🎉)')], default='LIKE', max_length=10),
        ),
    ]
