# Generated by Django 5.0.14 on 2026-01-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_emoji_based_reactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='answered_by',
            field=models.ForeignKey(blank=True, help_text='Who answered the question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_comment_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_question',
            field=models.BooleanField(default=False, help_text='Is this a question requiring moderator response?'),
        ),
        migrations.AddField(
            model_name='comment',
            name='question_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='OPEN', help_text='Status of question', max_length=20),
        ),
    ]
