export const BOOKS = [
  { number: 1,  name: "Genesis",        abbreviation: "Gen",   testament: "OT", chapters: 50  },
  { number: 2,  name: "Exodus",         abbreviation: "Exod",  testament: "OT", chapters: 40  },
  { number: 3,  name: "Leviticus",      abbreviation: "Lev",   testament: "OT", chapters: 27  },
  { number: 4,  name: "Numbers",        abbreviation: "Num",   testament: "OT", chapters: 36  },
  { number: 5,  name: "Deuteronomy",    abbreviation: "Deut",  testament: "OT", chapters: 34  },
  { number: 6,  name: "Joshua",         abbreviation: "Josh",  testament: "OT", chapters: 24  },
  { number: 7,  name: "Judges",         abbreviation: "Judg",  testament: "OT", chapters: 21  },
  { number: 8,  name: "Ruth",           abbreviation: "Ruth",  testament: "OT", chapters: 4   },
  { number: 9,  name: "1 Samuel",       abbreviation: "1Sam",  testament: "OT", chapters: 31  },
  { number: 10, name: "2 Samuel",       abbreviation: "2Sam",  testament: "OT", chapters: 24  },
  { number: 11, name: "1 Kings",        abbreviation: "1Kgs",  testament: "OT", chapters: 22  },
  { number: 12, name: "2 Kings",        abbreviation: "2Kgs",  testament: "OT", chapters: 25  },
  { number: 13, name: "1 Chronicles",   abbreviation: "1Chr",  testament: "OT", chapters: 29  },
  { number: 14, name: "2 Chronicles",   abbreviation: "2Chr",  testament: "OT", chapters: 36  },
  { number: 15, name: "Ezra",           abbreviation: "Ezra",  testament: "OT", chapters: 10  },
  { number: 16, name: "Nehemiah",       abbreviation: "Neh",   testament: "OT", chapters: 13  },
  { number: 17, name: "Esther",         abbreviation: "Esth",  testament: "OT", chapters: 10  },
  { number: 18, name: "Job",            abbreviation: "Job",   testament: "OT", chapters: 42  },
  { number: 19, name: "Psalms",         abbreviation: "Ps",    testament: "OT", chapters: 150 },
  { number: 20, name: "Proverbs",       abbreviation: "Prov",  testament: "OT", chapters: 31  },
  { number: 21, name: "Ecclesiastes",   abbreviation: "Eccl",  testament: "OT", chapters: 12  },
  { number: 22, name: "Song of Solomon",abbreviation: "Song",  testament: "OT", chapters: 8   },
  { number: 23, name: "Isaiah",         abbreviation: "Isa",   testament: "OT", chapters: 66  },
  { number: 24, name: "Jeremiah",       abbreviation: "Jer",   testament: "OT", chapters: 52  },
  { number: 25, name: "Lamentations",   abbreviation: "Lam",   testament: "OT", chapters: 5   },
  { number: 26, name: "Ezekiel",        abbreviation: "Ezek",  testament: "OT", chapters: 48  },
  { number: 27, name: "Daniel",         abbreviation: "Dan",   testament: "OT", chapters: 12  },
  { number: 28, name: "Hosea",          abbreviation: "Hos",   testament: "OT", chapters: 14  },
  { number: 29, name: "Joel",           abbreviation: "Joel",  testament: "OT", chapters: 3   },
  { number: 30, name: "Amos",           abbreviation: "Amos",  testament: "OT", chapters: 9   },
  { number: 31, name: "Obadiah",        abbreviation: "Obad",  testament: "OT", chapters: 1   },
  { number: 32, name: "Jonah",          abbreviation: "Jonah", testament: "OT", chapters: 4   },
  { number: 33, name: "Micah",          abbreviation: "Mic",   testament: "OT", chapters: 7   },
  { number: 34, name: "Nahum",          abbreviation: "Nah",   testament: "OT", chapters: 3   },
  { number: 35, name: "Habakkuk",       abbreviation: "Hab",   testament: "OT", chapters: 3   },
  { number: 36, name: "Zephaniah",      abbreviation: "Zeph",  testament: "OT", chapters: 3   },
  { number: 37, name: "Haggai",         abbreviation: "Hag",   testament: "OT", chapters: 2   },
  { number: 38, name: "Zechariah",      abbreviation: "Zech",  testament: "OT", chapters: 14  },
  { number: 39, name: "Malachi",        abbreviation: "Mal",   testament: "OT", chapters: 4   },
  { number: 40, name: "Matthew",        abbreviation: "Matt",  testament: "NT", chapters: 28  },
  { number: 41, name: "Mark",           abbreviation: "Mark",  testament: "NT", chapters: 16  },
  { number: 42, name: "Luke",           abbreviation: "Luke",  testament: "NT", chapters: 24  },
  { number: 43, name: "John",           abbreviation: "John",  testament: "NT", chapters: 21  },
  { number: 44, name: "Acts",           abbreviation: "Acts",  testament: "NT", chapters: 28  },
  { number: 45, name: "Romans",         abbreviation: "Rom",   testament: "NT", chapters: 16  },
  { number: 46, name: "1 Corinthians",  abbreviation: "1Cor",  testament: "NT", chapters: 16  },
  { number: 47, name: "2 Corinthians",  abbreviation: "2Cor",  testament: "NT", chapters: 13  },
  { number: 48, name: "Galatians",      abbreviation: "Gal",   testament: "NT", chapters: 6   },
  { number: 49, name: "Ephesians",      abbreviation: "Eph",   testament: "NT", chapters: 6   },
  { number: 50, name: "Philippians",    abbreviation: "Phil",  testament: "NT", chapters: 4   },
  { number: 51, name: "Colossians",     abbreviation: "Col",   testament: "NT", chapters: 4   },
  { number: 52, name: "1 Thessalonians",abbreviation: "1Thess",testament: "NT", chapters: 5   },
  { number: 53, name: "2 Thessalonians",abbreviation: "2Thess",testament: "NT", chapters: 3   },
  { number: 54, name: "1 Timothy",      abbreviation: "1Tim",  testament: "NT", chapters: 6   },
  { number: 55, name: "2 Timothy",      abbreviation: "2Tim",  testament: "NT", chapters: 4   },
  { number: 56, name: "Titus",          abbreviation: "Titus", testament: "NT", chapters: 3   },
  { number: 57, name: "Philemon",       abbreviation: "Phlm",  testament: "NT", chapters: 1   },
  { number: 58, name: "Hebrews",        abbreviation: "Heb",   testament: "NT", chapters: 13  },
  { number: 59, name: "James",          abbreviation: "Jas",   testament: "NT", chapters: 5   },
  { number: 60, name: "1 Peter",        abbreviation: "1Pet",  testament: "NT", chapters: 5   },
  { number: 61, name: "2 Peter",        abbreviation: "2Pet",  testament: "NT", chapters: 3   },
  { number: 62, name: "1 John",         abbreviation: "1John", testament: "NT", chapters: 5   },
  { number: 63, name: "2 John",         abbreviation: "2John", testament: "NT", chapters: 1   },
  { number: 64, name: "3 John",         abbreviation: "3John", testament: "NT", chapters: 1   },
  { number: 65, name: "Jude",           abbreviation: "Jude",  testament: "NT", chapters: 1   },
  { number: 66, name: "Revelation",     abbreviation: "Rev",   testament: "NT", chapters: 22  },
];

// Lookup: BOOK_BY_NUMBER[1] => { number: 1, name: "Genesis", ... }
export const BOOK_BY_NUMBER = Object.fromEntries(BOOKS.map(b => [b.number, b]));

// Lookup: BOOK_NUMBER_BY_NAME["Genesis"] => 1
export const BOOK_NUMBER_BY_NAME = Object.fromEntries(BOOKS.map(b => [b.name, b.number]));

export const OLD_TESTAMENT = BOOKS.filter(b => b.testament === "OT");
export const NEW_TESTAMENT = BOOKS.filter(b => b.testament === "NT");

export const DEFAULT_TRANSLATION = "KJV";
