# Generated by Django 5.0.14 on 2026-03-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('direction', models.CharField(default='ltr', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2)),
                ('chapter_count', models.PositiveSmallIntegerField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible.translation')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('translation', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.book')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.translation')),
            ],
            options={
                'indexes': [models.Index(fields=['translation', 'book_number', 'chapter'], name='bible_verse_transla_47241f_idx'), models.Index(fields=['translation', 'book_number', 'chapter', 'verse'], name='bible_verse_transla_5c125c_idx')],
                'unique_together': {('translation', 'book_number', 'chapter', 'verse')},
            },
        ),
    ]
