# Generated by Django 5.0.14 on 2026-03-07 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('SES', 'Amazon SES'), ('MAILGUN', 'Mailgun')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('smtp_host_env_var', models.CharField(blank=True, max_length=100)),
                ('smtp_port_env_var', models.CharField(blank=True, max_length=100)),
                ('smtp_user_env_var', models.CharField(blank=True, max_length=100)),
                ('smtp_password_env_var', models.CharField(blank=True, max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('api_key_env_var', models.CharField(blank=True, max_length=100)),
                ('api_endpoint', models.URLField(blank=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_from_name', models.CharField(blank=True, max_length=100)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Provider Config',
                'verbose_name_plural': 'Email Provider Configs',
                'db_table': 'email_provider_configs',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('email_type', models.CharField(choices=[('VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('SECURITY_ALERT', 'Security Alert'), ('TRANSACTIONAL', 'Transactional'), ('NOTIFICATION', 'Notification'), ('BULK', 'Bulk / Campaign')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='Django template syntax supported.')),
                ('text_body', models.TextField(blank=True, help_text='Plain-text fallback. Auto-generated from HTML if left blank.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['slug', '-version'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('email_type', models.CharField(choices=[('VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('SECURITY_ALERT', 'Security Alert'), ('TRANSACTIONAL', 'Transactional'), ('NOTIFICATION', 'Notification'), ('BULK', 'Bulk / Campaign')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('COMPLAINED', 'Complained (Spam)'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked')], db_index=True, default='PENDING', max_length=20)),
                ('provider_used', models.CharField(blank=True, choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('SES', 'Amazon SES'), ('MAILGUN', 'Mailgun')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='email.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'db_table': 'email_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('all_categories', models.BooleanField(db_index=True, default=False)),
                ('token', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(choices=[('LINK', 'Unsubscribe Link'), ('WEBHOOK', 'Provider Webhook'), ('MANUAL', 'Manual (Admin)'), ('API', 'API Request')], default='LINK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_unsubscribes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Unsubscribe',
                'verbose_name_plural': 'Email Unsubscribes',
                'db_table': 'email_unsubscribes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('action', models.CharField(choices=[('SUBSCRIBED', 'Subscribed'), ('UNSUBSCRIBED', 'Unsubscribed'), ('UPDATED', 'Preferences Updated'), ('RESUBSCRIBED', 'Re-subscribed')], db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Consent Log',
                'verbose_name_plural': 'Email Consent Logs',
                'db_table': 'email_consent_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', '-timestamp'], name='email_consent_email_ts_idx'), models.Index(fields=['user', '-timestamp'], name='email_consent_user_ts_idx'), models.Index(fields=['action', '-timestamp'], name='email_consent_action_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('BOUNCED', 'Bounced'), ('COMPLAINED', 'Complained (Spam)'), ('UNSUBSCRIBED', 'Unsubscribed')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('clicked_url', models.URLField(blank=True, max_length=2048)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email.emailmessage')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'db_table': 'email_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['message', 'event_type'], name='email_evt_msg_type_idx'), models.Index(fields=['event_type', '-timestamp'], name='email_evt_type_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('email_type', models.CharField(choices=[('VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('SECURITY_ALERT', 'Security Alert'), ('TRANSACTIONAL', 'Transactional'), ('NOTIFICATION', 'Notification'), ('BULK', 'Bulk / Campaign')], db_index=True, max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_seconds', models.PositiveIntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Rate Limit',
                'verbose_name_plural': 'Email Rate Limits',
                'db_table': 'email_rate_limits',
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['user', 'email_type', 'window_start'], name='email_rl_user_type_win_idx'), models.Index(fields=['email', 'email_type', 'window_start'], name='email_rl_addr_type_win_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['slug', 'is_active', '-version'], name='email_tmpl_slug_active_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['email_type', 'is_active'], name='email_tmpl_type_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('slug', 'version')},
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', '-created_at'], name='email_msg_status_cts_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['email_type', 'status'], name='email_msg_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['to_email', '-created_at'], name='email_msg_to_cts_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', '-created_at'], name='email_msg_user_cts_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['priority', 'status'], name='email_msg_pri_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'retry_count', 'scheduled_at'], name='email_msg_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='emailunsubscribe',
            index=models.Index(fields=['email', 'all_categories'], name='email_unsub_email_all_idx'),
        ),
    ]
