# Generated by Django 5.0.14 on 2026-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='circuit_open',
            field=models.BooleanField(default=False, help_text='True when the circuit breaker has tripped this provider.'),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='degraded_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which this provider is considered degraded.', null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='last_failure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
