# Generated by Django 5.0.14 on 2026-03-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_emailproviderconfig_circuit_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='rate_limit_key',
            field=models.CharField(blank=True, help_text='Redis rate-limit key that was checked for this message.', max_length=128),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='rendered_html',
            field=models.TextField(blank=True, help_text='Final HTML output after template rendering.'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='rendered_text',
            field=models.TextField(blank=True, help_text='Final plain-text output after template rendering.'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent render of this template.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, help_text='Optional parent template for subject/layout inheritance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='email.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this template has been rendered.'),
        ),
    ]
