/**
 * Material Icons to react-icons/md mapping
 * Maps Material Symbols icon names to react-icons Material Design equivalents
 */

import {
  MdHome,
  MdMenu,
  MdClose,
  MdArrowForward,
  MdArrowBack,
  MdChevronLeft,
  MdChevronRight,
  MdShare,
  MdBookmark,
  MdHeadphones,
  MdDescription,
  MdPlayArrow,
  MdPlayCircle,
  MdSearch,
  MdDelete,
  MdEdit,
  MdFavorite,
  MdAdd,
  MdRemove,
  MdSettings,
  MdPerson,
  MdDashboard,
  MdVisibility,
  MdVisibilityOff,
  MdInfo,
  MdWarning,
  MdError,
  MdErrorOutline,
  MdLogin,
  MdLogout,
  MdExpandMore,
  MdCollectionsBookmark,
  MdArticle,
  MdGroup,
  MdGroups,
  MdGroupWork,
  MdPeople,
  MdVolunteerActivism,
  MdCalendarToday,
  MdCalendarMonth,
  MdEvent,
  MdSchedule,
  MdLocationOn,
  MdViewList,
  MdViewKanban,
  MdViewWeek,
  MdGridView,
  MdTrendingUp,
  MdPublic,
  MdRssFeed,
  MdMenuBook,
  MdAutoStories,
  MdLibraryBooks,
  MdFolderOpen,
  MdForum,
  MdHourglassEmpty,
  MdBolt,
  MdConstruction,
  MdWorkspacePremium,
  MdSpa,
  MdFamilyRestroom,
  MdRefresh,
  MdMoreVert,
  MdCheck,
  MdCheckCircle,
  MdVerified,
  MdCircleNotifications,
  MdNotifications,
  MdSearchOff,
  MdHelp,
  MdHelpOutline,
  MdPsychology,
  MdSync,
  MdDownload,
  MdUpload,
  MdEditNote,
  MdNature,
  MdArrowUpward,
  MdArrowDownward,
  MdDragIndicator,
  MdDeleteForever,
  MdLockOpen,
  MdStar,
  MdAnalytics,
  MdOpenInNew,
  MdAddPhotoAlternate,
  MdEmergency,
  MdPlaylistAdd,
  MdImage,
  MdLink,
  MdArchive,
  MdMic,
  MdCampaign,
  MdPodcasts,
  MdBarChart,
  MdManageAccounts,
  MdMovie,
  MdFileCopy,
  MdToggleOn,
  MdLock,
  MdBackup,
  MdHistory,
  MdEmail,
  MdApi,
  MdPalette,
  MdGavel,
  MdPayments,
  MdStorage,
  MdPublish,
  MdBlock,
  MdCircle,
  MdChat,
  MdMail,
  MdCloud,
  MdSecurity,
} from 'react-icons/md';

export const iconMapping: Record<string, any> = {
  // Navigation
  home: MdHome,
  menu: MdMenu,
  close: MdClose,
  arrow_forward: MdArrowForward,
  arrow_back: MdArrowBack,
  chevron_left: MdChevronLeft,
  chevron_right: MdChevronRight,
  expand_more: MdExpandMore,
  
  // Social & Sharing
  share: MdShare,
  bookmark: MdBookmark,
  favorite: MdFavorite,
  forum: MdForum,
  psychology: MdPsychology,
  
  // Media
  play_arrow: MdPlayArrow,
  play_circle: MdPlayCircle,
  headphones: MdHeadphones,
  mic: MdMic,
  movie: MdMovie,
  description: MdDescription,
  article: MdArticle,
  menu_book: MdMenuBook,
  auto_stories: MdAutoStories,
  library_books: MdLibraryBooks,
  book: MdMenuBook,
  
  // Search & Visibility
  search: MdSearch,
  search_off: MdSearchOff,
  visibility: MdVisibility,
  visibility_off: MdVisibilityOff,
  public: MdPublic,
  
  // Content Management
  edit: MdEdit,
  edit_note: MdEditNote,
  delete: MdDelete,
  add: MdAdd,
  remove: MdRemove,
  campaign: MdCampaign,
  
  // Nature & Wellness
  nature: MdNature,
  self_improvement: MdSpa,
  
  // People & Groups
  person: MdPerson,
  people: MdPeople,
  group: MdGroup,
  groups: MdGroups,
  group_work: MdGroupWork,
  dashboard: MdDashboard,
  login: MdLogin,
  logout: MdLogout,
  family_restroom: MdFamilyRestroom,
  volunteer_activism: MdVolunteerActivism,
  
  // Collections & Organization
  collections_bookmark: MdCollectionsBookmark,
  folder_open: MdFolderOpen,
  grid_view: MdGridView,
  view_list: MdViewList,
  view_kanban: MdViewKanban,
  view_week: MdViewWeek,
  
  // Calendar & Time
  calendar_today: MdCalendarToday,
  calendar_month: MdCalendarMonth,
  event: MdEvent,
  schedule: MdSchedule,
  
  // Status & Notifications
  info: MdInfo,
  warning: MdWarning,
  error: MdError,
  error_outline: MdErrorOutline,
  check: MdCheck,
  check_circle: MdCheckCircle,
  verified: MdVerified,
  notifications: MdNotifications,
  notifications_active: MdCircleNotifications,
  
  // System
  settings: MdSettings,
  help: MdHelp,
  help_outline: MdHelpOutline,
  more_vert: MdMoreVert,
  refresh: MdRefresh,
  
  // Misc
  location_on: MdLocationOn,
  rss_feed: MdRssFeed,
  trending_up: MdTrendingUp,
  brand_family: MdFamilyRestroom,
  bolt: MdBolt,
  hourglass_empty: MdHourglassEmpty,
  construction: MdConstruction,
  spa: MdSpa,
  progress_activity: MdSync,
  
  // Additional
  download: MdDownload,
  upload: MdUpload,
  workspace_premium: MdWorkspacePremium,
  
  // Additional icons
  keyboard_arrow_up: MdArrowUpward,
  keyboard_arrow_down: MdArrowDownward,
  drag_indicator: MdDragIndicator,
  delete_forever: MdDeleteForever,
  lock_open: MdLockOpen,
  star: MdStar,
  analytics: MdAnalytics,
  open_in_new: MdOpenInNew,
  add_photo_alternate: MdAddPhotoAlternate,
  emergency: MdEmergency,
  playlist_add: MdPlaylistAdd,
  image: MdImage,
  link: MdLink,
  archive: MdArchive,
  account_tree: MdGroups,
  podcasts: MdPodcasts,
  groups_2: MdGroups,
  manage_accounts: MdManageAccounts,
  bar_chart: MdBarChart,
  file_copy: MdFileCopy,
  toggle_on: MdToggleOn,
  lock: MdLock,
  backup: MdBackup,
  history: MdHistory,
  email: MdEmail,
  api: MdApi,
  palette: MdPalette,
  gavel: MdGavel,
  payments: MdPayments,
  storage: MdStorage,
  publish: MdPublish,
  block: MdBlock,
  circle: MdCircle,
  chat: MdChat,
  mail: MdMail,
  cloud: MdCloud,
  security: MdSecurity,
};

/**
 * Get icon component by name
 * @param name - Material icon name
 * @returns React component for the icon
 */
export const getIcon = (name: string): React.ComponentType<any> | null => {
  return iconMapping[name] || null;
};

/**
 * Supported icon names
 */
export const supportedIcons = Object.keys(iconMapping);
