# Generated by Django 5.0.14 on 2026-03-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_tra_status_137fde_idx',
            old_name='payment_tra_status_478531_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_tra_referen_451c50_idx',
            old_name='payment_tra_referen_b5f4bd_idx',
        ),
    ]
