# Generated by Django 5.0.14 on 2026-03-06 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payment_tra_status_478531_idx_payment_tra_status_137fde_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in the smallest currency unit')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('purpose', models.CharField(help_text='Purpose of payment (e.g., donation, subscription, purchase)', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(help_text='Intent expires at this time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INTENT_CREATED', 'Payment Intent Created'), ('INTENT_EXPIRED', 'Payment Intent Expired'), ('TX_INITIALIZED', 'Transaction Initialized'), ('TX_VERIFICATION_STARTED', 'Verification Started'), ('TX_VERIFICATION_SUCCESS', 'Verification Successful'), ('TX_VERIFICATION_FAILED', 'Verification Failed'), ('WEBHOOK_RECEIVED', 'Webhook Received'), ('WEBHOOK_VALIDATED', 'Webhook Signature Valid'), ('WEBHOOK_REJECTED', 'Webhook Rejected'), ('WEBHOOK_PROCESSED', 'Webhook Processed'), ('WEBHOOK_DUPLICATE', 'Duplicate Webhook (Idempotent)'), ('GATEWAY_ERROR', 'Gateway Error'), ('NETWORK_ERROR', 'Network Error'), ('VALIDATION_ERROR', 'Validation Error'), ('FRAUD_DETECTED', 'Potential Fraud Detected'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded')], db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.paymenttransaction')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.paymentintent')),
            ],
            options={
                'db_table': 'payment_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['email', 'is_used'], name='payment_int_email_970920_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['expires_at'], name='payment_int_expires_65ff25_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='payment_aud_event_t_12bae4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['transaction', 'event_type'], name='payment_aud_transac_4a9219_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['severity', 'created_at'], name='payment_aud_severit_af4eb2_idx'),
        ),
    ]
