# Generated by Django 5.0.14 on 2026-03-28 21:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0002_normalize_choices'),
        ('payments', '0005_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringGivingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('giving_title', models.CharField(blank=True, max_length=200)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in the smallest currency unit')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], db_index=True, default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('next_payment_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('paystack_plan_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('paystack_subscription_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('inferred_from_metadata', models.BooleanField(default=False)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giving_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_giving_plans', to='giving.givingitem')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_recurring_plans', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_giving_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_giving_plans',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='rec_plan_usr_st_idx'), models.Index(fields=['next_payment_at'], name='rec_plan_nextpay_idx'), models.Index(fields=['paystack_subscription_code'], name='rec_plan_subcode_idx')],
            },
        ),
    ]
