# Generated by Django 5.0.14 on 2026-03-14 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fiscal_year', models.IntegerField(db_index=True, default=2025)),
                ('icon', models.CharField(default='account_balance', max_length=50)),
                ('color', models.CharField(default='#64748b', help_text='Hex color code', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'department'],
                'indexes': [models.Index(fields=['fiscal_year', 'department'], name='payouts_bud_fiscal__46670b_idx'), models.Index(fields=['fiscal_year', 'display_order'], name='payouts_bud_fiscal__3601a4_idx')],
                'unique_together': {('department', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='FundReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('icon', models.CharField(default='account_balance_wallet', max_length=50)),
                ('color', models.CharField(default='#94a3b8', help_text='Hex color code', max_length=7)),
                ('note', models.CharField(blank=True, help_text='Purpose/description of the fund', max_length=200)),
                ('fiscal_year', models.IntegerField(db_index=True, default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fiscal_year'], name='payouts_fun_fiscal__d116f7_idx')],
            },
        ),
    ]
